sudo: false
language: ruby
rvm:
- 2.5.1
- ruby-head
gemfile: "gems.rb"
before_install: gem install bundler --no-document
before_script:
- "ruby lib/initial_setup.rb ../.travis_setup"
- "psql -c 'create database innovate_test;' -U postgres"
- "rails db:migrate"
matrix:
  allow_failures:
  - rvm: ruby-head
