language: ruby
rvm:
- 3.1.2
gemfile: "gems.rb"
addons:
  postgresql: "10"
before_install:
- nvm install 10
before_script:
- ruby lib/initial_setup.rb ../.travis_setup
- cp config/.travis.database.yml config/database.yml
- psql -c 'create database travis_test;' -U postgres
- rails db:migrate
