language: ruby
rvm:
- 2.6.3
- 3.0.0
- ruby-head
gemfile: "gems.rb"
addons:
  postgresql: "9.6"
before_script:
- ruby lib/initial_setup.rb ../.travis_setup
- cp config/.travis.database.yml config/database.yml
- psql -c 'create database travis_test;' -U postgres
- rails db:migrate
matrix:
  allow_failures:
  - rvm: ruby-head
